#!/usr/bin/env python3
"""
Coach Tool: Telemetry Analysis (FACTS ONLY)
Generated by Little Padawan

Purpose: Analyze detailed telemetry data (Speed, Brake, Throttle, G-forces)
to provide factual insights on driving technique.

Usage:
    python tools/coach/analyze_telemetry.py <telemetry_file.csv>

Output: JSON with factual telemetry data
"""

import sys
import json
import pandas as pd
import numpy as np
from pathlib import Path

def analyze_telemetry_facts(csv_path):
    """
    Analyze telemetry and return FACTS ONLY.
    
    Metrics:
    - Top Speed
    - Minimum Corner Speeds
    - Braking Efficiency (Max G, Average Brake Pressure)
    - Throttle Smoothness (Stdev of Throttle while > 0)
    """
    try:
        df = pd.read_csv(csv_path)
    except Exception as e:
        return {"error": f"Failed to load CSV: {str(e)}"}
        
    # Check if this is actually a telemetry file
    required_cols = ['Speed', 'Brake', 'Throttle', 'LatAccel', 'LongAccel']
    if not all(col in df.columns for col in required_cols):
        return {"error": "Not a telemetry file. Missing required columns."}
    
    # Helper to safely get scalar float from potential NaN
    def safe_float(val):
        if pd.isna(val):
            return 0.0
        return float(val)

    # 1. Speed Analysis
    top_speed = safe_float(df['Speed'].max())
    # Find local minima for corner speeds (simple approach: speed < threshold and is local min)
    # Using a rolling window to smooth noise could be good, but keeping it simple for now
    
    # 2. Braking Analysis
    braking_zones = df[df['Brake'] > 5] # Brake pressure > 5%
    max_brake_pressure = safe_float(braking_zones['Brake'].max()) if not braking_zones.empty else 0.0
    avg_brake_pressure = safe_float(braking_zones['Brake'].mean()) if not braking_zones.empty else 0.0
    
    # Max Deceleration (LongAccel is usually negative for braking)
    # Some sims use positive for braking, but typically it's negative Gs.
    # We'll take the minimum value (most negative)
    max_braking_g = safe_float(df['LongAccel'].min())
    
    # 3. Throttle Analysis
    throttle_zones = df[df['Throttle'] > 5]
    avg_throttle = safe_float(throttle_zones['Throttle'].mean()) if not throttle_zones.empty else 0.0
    
    # 4. Cornering Gs
    # Max Lateral G (absolute value)
    max_lat_g = safe_float(df['LatAccel'].abs().max())
    avg_lat_g = safe_float(df['LatAccel'].abs().mean())
    
    facts = {
        "speed": {
            "top_speed": round(top_speed, 2),
            # "min_speeds": [] # TODO: Add sophisticated corner detection later
        },
        "braking": {
            "max_pressure": round(max_brake_pressure, 2),
            "avg_pressure_in_zones": round(avg_brake_pressure, 2),
            "max_long_g": round(max_braking_g, 2)
        },
        "throttle": {
            "avg_application": round(avg_throttle, 2)
        },
        "cornering": {
            "max_lat_g": round(max_lat_g, 2),
            "avg_lat_g": round(avg_lat_g, 2)
        },
        "stats": {
            "total_samples": len(df),
            "duration_s": round(len(df) / 60.0, 2) # Approximation if Hz is 60, need time col for accuracy
        }
    }
    
    return facts

def main():
    if len(sys.argv) < 2:
        print(json.dumps({"error": "Usage: python analyze_telemetry.py <file.csv>"}))
        sys.exit(1)
        
    csv_path = sys.argv[1]
    if not Path(csv_path).exists():
        print(json.dumps({"error": f"File not found: {csv_path}"}))
        sys.exit(1)
        
    facts = analyze_telemetry_facts(csv_path)
    print(json.dumps(facts, indent=2))

if __name__ == "__main__":
    main()
